config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, path: :account
  resources :posts, :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, User, parent_id: user.id
    user.permissions.each do |permission|
      can permission.action.to_sym, (permission.resource.constantize rescue permission.resource.to_sym)
    end
  end
end

app/models/concerns/permission/policy.rb
require 'active_support/concern'

class Permission
  module Policy
    extend ActiveSupport::Concern

    class_methods do
      @@policies = []

      def policies
        @@policies
      end

      def policy_exist? policy
        action, resource = policy.split
        exists?(action: action, resource: resource)
      end

      def add_policy *policies
        @@policies |= policies
      end

      def add_policy_with_resource *models
        models.each do |model|
          @@policies |= %w[create read update destroy].map!{|action| "#{action} #{model}"}
        end
      end
    end
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  include Permission::Policy
  belongs_to :user
  add_policy_with_resource Post, User
  add_policy 'kill man', 'drink water', 'manage all'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :parent, class_name: User
  has_many :children, class_name: User, foreign_key: :parent_id
  has_many :permissions, dependent: :destroy
  delegate :policy_exist?, to: :permissions

  def set_permission action, resource
    permissions.find_or_create_by! action: action, resource: resource
  end

  def parent?
    parent_id.nil?
  end

  def child?
    not parent?
  end

  def policies
    permissions.map{ |p| p.policy }
  end

  def policies= values
    self.permissions = values.map! do |v|
      action, resource = v.split
      Permission.new action: action, resource: resource
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to request.referer || root_url, alert: '你沒有權限這麼做' #exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = if params[:button] == 'top_user'
      authorize! :manage, :all
      User.new user_params
    else
      current_user.children.new user_params
    end
    if @user.save
      redirect_to edit_user_path(@user), notice: '已新增！'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to edit_user_path(@user), notice: '已更新！'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to User, notice: '刪除囉'
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, policies: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PermissionDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to '首頁', root_path %></li>
      <li><%= link_to '使用者', users_path %></li>
      <li><%= link_to '文章', posts_path %></li>
      <% if user_signed_in? %>
        <li>歡迎回來 <%= current_user.email %> | <%= link_to '登出', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to '註冊', new_user_registration_path %></li>
        <li><%= link_to '登入', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.new_record? %>
    <%= f.label :email %>
    <%= f.email_field :email %><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>
  <% end %>

  <h2>Permissions</h2>

  <% Permission.policies.each_with_index do |policy, index| %>
    <%= label_tag policy %>
    <%= check_box_tag "user[policies][]", policy, @user.policy_exist?(policy) %><br>
  <% end %>
  <% if @user.new_record? %>
    <%= f.button '新增一般帳號', value: :top_user %>
    <%= f.button '新增子帳號', value: :child %>
  <% else %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render 'form' %>

<h2>測試權限</h2>

可以喝水？：<%= can? :drink, :water %> <br>
可以殺人？：<%= can? :kill, :man %>

app/views/users/index.html.erb
<h1>使用者清單</h1>

<%= link_to '新增使用者', new_user_path %>

<ul>
<% @users.each do |user| %>
  <li><%= user.email %> | <%= link_to '編輯', edit_user_path(user) %> | <%= link_to '刪除', user, method: :delete %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>新增使用者</h1>

<%= render 'form' %>

<h2></h2>